"use client";
import Image from "next/image";
import {useState} from "react";

type Option={value:string;label:string};
type AssetView={id:string;fileName:string;projectPath:string;width:number;height:number;sizeBytes:number;transparentBackground:boolean;guessedBrand:string;guessedProduct:string;guessedSize:string|null;guessedFlavor:string|null;confidence:number;reviewStatus:string;adopted:boolean;note:string|null};
export function AssetReviewCard({asset,options}:{asset:AssetView;options:Option[]}){
 const[target,setTarget]=useState(options[0]?.value||"");const[role,setRole]=useState("PRIMARY");const[msg,setMsg]=useState("");
 async function save(body:Record<string,unknown>){const r=await fetch("/api/admin/assets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({assetId:asset.id,...body})});const j=await r.json();setMsg(r.ok?"已保存":j.error);if(r.ok)setTimeout(()=>location.reload(),450)}
 const [productId,variantId]=target.split("|");
 return <article className="card"><div className="asset-thumb"><Image src={asset.projectPath} alt={asset.fileName} width={asset.width} height={asset.height}/></div><h3>{asset.fileName}</h3><p className="muted">{asset.width} × {asset.height} · {(asset.sizeBytes/1024).toFixed(0)} KB · {asset.transparentBackground?"透明背景":"非透明"}</p><p>{asset.guessedBrand} · {asset.guessedProduct}<br/>{asset.guessedSize||"规格待确认"} · {asset.guessedFlavor||"口味待确认"}</p><p><span className="tag">{asset.reviewStatus}</span>　置信度 {Math.round(asset.confidence*100)}%</p><div className="filters"><button className="btn subtle" onClick={()=>save({status:"ADOPTED"})}>已采用</button><button className="btn subtle" onClick={()=>save({status:"PENDING"})}>待确认</button><button className="btn subtle" onClick={()=>save({status:"REJECTED"})}>不使用</button></div><label>绑定商品或 SKU</label><select className="field" value={target} onChange={e=>setTarget(e.target.value)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select><select className="field" style={{marginTop:8}} value={role} onChange={e=>setRole(e.target.value)}><option value="PRIMARY">商品主图</option><option value="FRONT">正面图</option><option value="BACK">背面图</option><option value="NUTRITION">营养成分图</option><option value="DETAIL">细节图</option><option value="VERSION">版本说明图</option></select><button className="btn" style={{marginTop:10}} onClick={()=>save({status:"ADOPTED",productId,variantId:variantId||null,role})}>保存绑定</button><p className="muted">{msg||asset.note}</p></article>
}
